# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myinstagramapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='time',
            new_name='time_count',
        ),
    ]
