# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinstagramapp', '0003_auto_20181003_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=60),
        ),
    ]
