# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myinstagramapp', '0004_auto_20181004_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='myinstagramapp.Profile'),
            preserve_default=False,
        ),
    ]
