# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myinstagramapp', '0004_auto_20181003_1539'),
        ('myinstagramapp', '0005_image_profile'),
    ]

    operations = [
    ]
